knowage:
    image: snecommerce/knowage-server-docker:6.1.1-custom
    links:
        - knowagedb:db
    ports:
        - "8080:8080"
    environment:
        - WAIT_MYSQL=true
        - PUBLIC_ADDRESS=laborex.kaylene-group.com
        - PUBLIC_PORT=80
        - MYSQL_USER=knowageuser
        - MYSQL_PASSWORD=knowagepassword
        - MYSQL_DATABASE=knowagedb
        - MYSQL_ROOT_PASSWORD=knowagerootpassword
        # - JVM_OPTS=-Xmx512m -Xms1024m -XX:MaxPermSize=512m
        # export JAVA_OPTS="$JAVA_OPTS -Xms1024m -Xmx2048m -XX:MaxPermSize=512m"


knowagedb:
    image: mysql:5.5
    environment:
        - MYSQL_USER=knowageuser
        - MYSQL_PASSWORD=knowagepassword
        - MYSQL_DATABASE=knowagedb
        - MYSQL_ROOT_PASSWORD=knowagerootpassword